
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings
class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('section', models.CharField(choices=[('ECDE','ECDE'),('LOWER','Lower Primary'),('UPPER','Upper Primary'),('JUNIOR','Junior Secondary')], max_length=10)),
                    ('name', models.CharField(max_length=64)),
                    ('order', models.PositiveSmallIntegerField())],
            options={'ordering':['section','order'],'unique_together':{('section','name')}}),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('name', models.CharField(max_length=9, unique=True))],
            options={'ordering':['-name']}),
        migrations.CreateModel(
            name='Term',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('number', models.PositiveSmallIntegerField(choices=[(1,'Term 1'),(2,'Term 2'),(3,'Term 3')])),
                    ('start_date', models.DateField(null=True, blank=True)),
                    ('end_date', models.DateField(null=True, blank=True)),
                    ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.academicyear'))],
            options={'ordering':['year__name','number'],'unique_together':{('year','number')}}),
        migrations.CreateModel(
            name='Student',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('admission_no', models.CharField(max_length=20, unique=True, db_index=True)),
                    ('first_name', models.CharField(max_length=64)),
                    ('middle_name', models.CharField(max_length=64, blank=True)),
                    ('last_name', models.CharField(max_length=64)),
                    ('dob', models.DateField(null=True, blank=True)),
                    ('birth_cert_no', models.CharField(max_length=64, blank=True)),
                    ('upi', models.CharField(max_length=64, blank=True)),
                    ('father_name', models.CharField(max_length=128, blank=True)),
                    ('mother_name', models.CharField(max_length=128, blank=True)),
                    ('guardian_name', models.CharField(max_length=128, blank=True)),
                    ('guardian_relationship', models.CharField(max_length=64, blank=True)),
                    ('contact1', models.CharField(max_length=64, blank=True)),
                    ('residence', models.TextField(blank=True)),
                    ('boarding_status', models.CharField(choices=[('DAY','Day'),('BOARDING','Boarding')], default='DAY', max_length=10)),
                    ('status', models.CharField(choices=[('ACTIVE','Active'),('TRANSFERRED','Transferred'),('ALUMNI','Alumni')], default='ACTIVE', max_length=12)),
                    ('enrollment_class', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='core.classlevel')),
                    ('term_enrolled', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='core.term')),
                    ('year_enrolled', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='core.academicyear'))],
            options={'ordering':['last_name','first_name']}),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('boarding_status', models.CharField(choices=[('DAY','Day'),('BOARDING','Boarding')], max_length=10)),
                    ('amount_kes', models.DecimalField(max_digits=12, decimal_places=2)),
                    ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.classlevel')),
                    ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.term'))],
            options={'unique_together':{('term','class_level','boarding_status')}}),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('date', models.DateField()),
                    ('entry_type', models.CharField(max_length=12, choices=[('INVOICE','Invoice'),('PAYMENT','Payment'),('REVERSAL','Reversal')])),
                    ('source', models.CharField(max_length=16, choices=[('SYSTEM','System'),('CASH','Cash'),('BANK_CSV','Bank CSV'),('MPESA_CSV','M-Pesa CSV'),('MANUAL_CORRECTION','Manual Correction')])),
                    ('mode', models.CharField(max_length=10, choices=[('CASH','Cash'),('MPESA','M-Pesa'),('BANK','Bank')], null=True, blank=True)),
                    ('amount_kes', models.DecimalField(max_digits=12, decimal_places=2)),
                    ('reference', models.CharField(max_length=64, blank=True)),
                    ('memo', models.TextField(blank=True)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.student')),
                    ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.term')),
                    ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_entries', to=settings.AUTH_USER_MODEL))],
            options={'ordering':['-date','-created_at']}),
        migrations.AddIndex(model_name='ledgerentry', index=models.Index(fields=['student','term'], name='ledger_st_term_idx')),
        migrations.AddIndex(model_name='ledgerentry', index=models.Index(fields=['date'], name='ledger_date_idx')),
        migrations.CreateModel(
            name='Payment',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('date', models.DateField()),
                    ('mode', models.CharField(max_length=10, choices=[('CASH','Cash'),('MPESA','M-Pesa'),('BANK','Bank')])),
                    ('amount_kes', models.DecimalField(max_digits=12, decimal_places=2)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('edit_count_today', models.PositiveSmallIntegerField(default=0)),
                    ('reference', models.CharField(max_length=64, blank=True)),
                    ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.student')),
                    ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.term')),
                    ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(
            name='PaymentEditLog',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('edited_at', models.DateTimeField(auto_now_add=True)),
                    ('change_summary', models.JSONField(null=True, blank=True)),
                    ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                    ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.payment'))]),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('channel', models.CharField(max_length=10, choices=[('BANK','Bank'),('MPESA','M-Pesa')])),
                    ('filename', models.CharField(max_length=200)),
                    ('imported_at', models.DateTimeField(auto_now_add=True)),
                    ('status', models.CharField(max_length=10, choices=[('PENDING','Pending'),('PROCESSED','Processed'),('PARTIAL','Partial'),('FAILED','Failed')], default='PENDING')),
                    ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(
            name='ImportRow',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('date', models.DateField(null=True, blank=True)),
                    ('amount', models.DecimalField(null=True, blank=True, max_digits=12, decimal_places=2)),
                    ('reference', models.CharField(max_length=64, blank=True)),
                    ('payer_phone', models.CharField(max_length=32, blank=True)),
                    ('payer_name', models.CharField(max_length=128, blank=True)),
                    ('narrative', models.TextField(blank=True)),
                    ('match_strategy', models.CharField(max_length=16, choices=[('ADMISSION','Admission'),('NAME_CLASS','Name+Class'),('MANUAL','Manual'),('NONE','None')], default='NONE')),
                    ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.importbatch')),
                    ('matched_student', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
                    ('posted_entry', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='core.ledgerentry'))]),
        migrations.AddIndex(model_name='importrow', index=models.Index(fields=['reference'], name='import_ref_idx')),
        migrations.AddIndex(model_name='importrow', index=models.Index(fields=['payer_phone'], name='import_phone_idx')),
        migrations.CreateModel(
            name='NeedsReview',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('reason', models.CharField(max_length=200)),
                    ('notes', models.TextField(blank=True)),
                    ('resolved_at', models.DateTimeField(null=True, blank=True)),
                    ('import_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.importrow')),
                    ('resolved_by', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(
            name='Expense',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('date', models.DateField()),
                    ('amount_kes', models.DecimalField(max_digits=12, decimal_places=2)),
                    ('category', models.CharField(max_length=64)),
                    ('vendor', models.CharField(max_length=128, blank=True)),
                    ('mode', models.CharField(max_length=10, choices=[('CASH','Cash'),('MPESA','M-Pesa'),('BANK','Bank')])),
                    ('notes', models.TextField(blank=True)),
                    ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.term'))]),
        migrations.CreateModel(
            name='Budget',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('category', models.CharField(max_length=64)),
                    ('amount_kes', models.DecimalField(max_digits=12, decimal_places=2)),
                    ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.term'))],
            options={'unique_together':{('term','category')}}),
        migrations.CreateModel(
            name='AuditLog',
            fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                    ('action', models.CharField(max_length=64)),
                    ('entity', models.CharField(max_length=64)),
                    ('entity_id', models.CharField(max_length=64)),
                    ('meta', models.JSONField(null=True, blank=True)),
                    ('at', models.DateTimeField(auto_now_add=True)),
                    ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))],
            options={'ordering':['-at']}),
    ]
