# Generated by Django 5.1.12 on 2025-09-21 01:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importrow',
            new_name='core_import_referen_583286_idx',
            old_name='import_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='importrow',
            new_name='core_import_payer_p_e9b66a_idx',
            old_name='import_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='core_ledger_student_7b0991_idx',
            old_name='ledger_st_term_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='core_ledger_date_744a5c_idx',
            old_name='ledger_date_idx',
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Ordering within section'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('CASH', 'Cash'), ('BANK_CSV', 'Bank CSV'), ('MPESA_CSV', 'M-Pesa CSV'), ('MANUAL_CORRECTION', 'Manual Correction')], max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'term', 'date'], name='core_paymen_student_b3b507_idx'),
        ),
    ]
