# Generated by Django 5.1.12 on 2025-09-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-name'], 'verbose_name': 'Academic year', 'verbose_name_plural': 'Academic years'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-at'], 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='classlevel',
            options={'ordering': ['section', 'order'], 'verbose_name_plural': 'Class levels'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'verbose_name': 'Fee structure', 'verbose_name_plural': 'Fee structures'},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={'verbose_name': 'Import batch', 'verbose_name_plural': 'Import batches'},
        ),
        migrations.AlterModelOptions(
            name='importrow',
            options={'verbose_name': 'Import row', 'verbose_name_plural': 'Import rows'},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Ledger entry', 'verbose_name_plural': 'Ledger entries'},
        ),
        migrations.AlterModelOptions(
            name='needsreview',
            options={'verbose_name': 'Needs review', 'verbose_name_plural': 'Needs reviews'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenteditlog',
            options={'verbose_name': 'Payment edit log', 'verbose_name_plural': 'Payment edit logs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['year__name', 'number'], 'verbose_name_plural': 'Terms'},
        ),
    ]
